name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.16.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run buildWin

      - name: Archive build artifacts
        run: tar -czvf buildWin.tar.gz ./dist

      - name: Setup Inno Setup
        run: choco install innosetup

      - name: Compile Inno Setup Script
        run: "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" /Q /Ooutput /F"Setup" path_to_your_script.iss

      - name: Upload build and installer artifacts
        uses: actions/upload-artifact@v3
        with:
          name: buildWin
          path: |
            buildWin.tar.gz
            output/Setup.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build and installer artifacts
        uses: actions/download-artifact@v3
        with:
          name: buildWin

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            buildWin.tar.gz
            output/Setup.exe
          asset_name: |
            buildWin.tar.gz
            Setup.exe
          asset_content_type: application/octet-stream