name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.16.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Create dist directory
        run: mkdir -p ./dist

      - name: Debug npm scripts
        run: |
          echo "Executing npm run create-latest-json"
          npm run create-latest-json

      - name: Install Wine
        run: sudo dpkg --add-architecture i386 && sudo apt update && sudo apt install -y wine64 wine32

      - name: Build application
        run: npm run dist

      - name: Create latest.yml
        run: npm run create-latest-yml

      - name: Create latest.json
        run: npm run create-latest-json

      - name: Generate blockmap
        run: npm run generate-blockmap

      - name: Generate checksum
        run: npm run generate-checksum

      - name: Create a new directory for release files
        run: mkdir -p ./dist/release-files
        
      - name: Archivate program files
        run: |
          cd ./dist/slpb-win32-x64 && zip -r ../../slpb-win32-x64.zip ./*
        
      - name: List files in dist directory (Debug)
        run: ls -la ./dist
        
      - name: List files in root directory (Debug)
        run: ls -la
        
      - name: Move files to release directory
        run: |
          mv slpb-win32-x64.zip ./dist/release-files/
          mv latest.yml ./dist/release-files/
          mv latest.json ./dist/release-files/
          mv slpb.blockmap ./dist/release-files/
          mv LICENSE ./dist/release-files/
          mv README.md ./dist/release-files/

      - name: List files in release directory (Debug)
        run: ls -la ./dist/release-files
        
      - name: Upload build artifact (release-files)
        uses: actions/upload-artifact@v3
        with:
          name: release-files
          path: ./dist/release-files

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download release files artifact
      uses: actions/download-artifact@v3
      with:
        name: release-files

    - name: Extract Version from Tag
      id: extract_version
      run: echo "VERSION=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
        draft: true
        prerelease: false

    - name: Upload Release Assets (Individual Files)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-files/slpb-win32-x64.zip
        asset_name: slpb-win32-x64.zip
        asset_content_type: application/zip

    - name: Upload Release Assets (latest.yml)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-files/latest.yml
        asset_name: latest.yml
        asset_content_type: text/yaml

    - name: Upload Release Assets (LICENSE)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-files/LICENSE
        asset_name: LICENSE
        asset_content_type: text/plain

    - name: Upload Release Assets (README.md)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-files/README.md
        asset_name: README.md
        asset_content_type: text/markdown

    - name: Upload Release Assets (latest.json)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-files/latest.json
        asset_name: latest.json
        asset_content_type: application/json

    - name: Upload Release Assets (slpb.blockmap)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-files/slpb.blockmap
        asset_name: slpb.blockmap
        asset_content_type: application/octet-stream