name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.16.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run buildWin
      
      - name: List files in dist directory
        run: |
          ls -la ./dist
          ls ./dist

      - name: Create zip archive with exe
        run: |
          mkdir -p zip_temp
          cp ./dist/slpb-win32-x64/*.exe zip_temp/
          zip -r ServerListPlayBetter.zip zip_temp/


      - name: Upload build artifact (zip)
        uses: actions/upload-artifact@v3
        with:
          name: ServerListPlayBetter
          path: ServerListPlayBetter.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download zip artifact
        uses: actions/download-artifact@v3
        with:
          name: ServerListPlayBetter

      - name: Move downloaded artifacts
        run: |
          mkdir -p artifacts
          mv ServerListPlayBetter.zip ./artifacts/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.sha }}
          release_name: Release v${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (zip)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/ServerListPlayBetter.zip
          asset_name: ServerListPlayBetter.zip
          asset_content_type: application/zip