name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.16.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run buildWinP

      - name: Package application
        run: npm run dist

      - name: List files in dist directory
        run: |
          ls -la ./dist
          ls ./dist
          ls -la ./dist/slpb-win32-x64

      - name: Create zip archive with exe
        run: |
          mkdir -p zip_temp
          cp -r ./dist/slpb-win32-x64/* zip_temp/
          zip -r ServerListPlayBetter.zip zip_temp/*

      - name: Upload build artifact (zip)
        uses: actions/upload-artifact@v3
        with:
          name: ServerListPlayBetter
          path: ServerListPlayBetter.zip

      - name: Upload latest.yml artifact
        uses: actions/upload-artifact@v3
        with:
          name: latest-yml
          path: ./dist/latest.yml

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download zip artifact
        uses: actions/download-artifact@v3
        with:
          name: ServerListPlayBetter

      - name: Download latest.yml artifact
        uses: actions/download-artifact@v3
        with:
          name: latest-yml

      - name: Move downloaded artifacts
        run: |
          mkdir -p artifacts
          mv ServerListPlayBetter.zip ./artifacts/
          mv latest.yml ./artifacts/

      - name: Extract Version from Tag
        id: extract_version
        run: echo "##[set-output name=VERSION;]$(echo ${GITHUB_REF##*/})"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.VERSION }}
          release_name: ${{ steps.extract_version.outputs.VERSION }}
          draft: false
          prerelease: false 

      - name: Upload Release Asset (zip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/ServerListPlayBetter.zip
          asset_name: ServerListPlayBetter.zip
          asset_content_type: application/zip

      - name: Upload Release Asset (latest.yml)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/latest.yml
          asset_name: latest.yml
          asset_content_type: text/yaml

permissions:
  id-token: write
  checks: write
  contents: write